create table tbl_derby(
	a1 INTEGER generated by default as identity, 
	a2 bigint,
	a3 blob,
	a4 char,
	a5 char(32) for bit data,
	a6 clob,
	a7 date,
	a8 decimal,
	a9 double,
	a10 double precision,	
	a11 float,
	a12 integer,
	a13 long varchar,
	a14 long varchar for bit data,
	a15 numeric,
	a16 real,
	a17 smallint,
	a18 time,
	a19 timestamp,
	a20 varchar(32),
	a21 varchar(255) for bit data
);


====================

create table tbl_derby(
	a1 INTEGER generated by default as identity, 
	-- NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	a2 bigint,
	a3 blob,
	a4 char,
	-- The default length for a CHAR FOR BIT DATA type is 1., and the maximum size of length is 254 bytes.
	-- java.sql.Types.BINARY
	a5 char(32) for bit data,
	a6 clob,
	a7 date,
	a8 decimal,
	a9 double,
	a10 double precision,	
	a11 float,
	a12 integer,
	a13 long varchar,
	-- @see varchar for bit data 
	a14 long varchar for bit data,
	a15 numeric,
	a16 real,
	a17 smallint,
	a18 time,
	a19 timestamp,
	a20 varchar,
	-- The maximum size of the length value is 32,672 bytes.
	-- Unlike the case for the CHAR FOR BIT DATA type, there is no default length for a VARCHAR FOR BIT DATA type
	-- java.sql.Types.VARBINARY
	a21 varchar(255) for bit data
);