
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Dec 17 17:34:29 PST 2001
//----------------------------------------------------

package sql4j.parser;

//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Dec 17 17:34:29 PST 2001
//----------------------------------------------------

//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Dec 17 17:34:29 PST 2001
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 5;
  public static final int TIMES = 104;
  public static final int REAL = 64;
  public static final int FROM = 34;
  public static final int GT = 112;
  public static final int COLUMN = 90;
  public static final int CLOSE = 12;
  public static final int TIMESTAMP = 75;
  public static final int GROUP = 37;
  public static final int ERR = 87;
  public static final int WORK = 86;
  public static final int TABLE = 74;
  public static final int ROLLBACK = 66;
  public static final int GE = 111;
  public static final int PERIOD = 95;
  public static final int SEMI = 100;
  public static final int INDICATOR = 40;
  public static final int INT_NUM = 121;
  public static final int ASC = 6;
  public static final int NAME = 120;
  public static final int VARREF = 119;
  public static final int LIKE = 48;
  public static final int SCHEMA = 67;
  public static final int COMMA = 93;
  public static final int FOUND = 33;
  public static final int RBRACE = 99;
  public static final int JOIN = 45;
  public static final int RPAREN = 97;
  public static final int REFERENCES = 65;
  public static final int LT = 116;
  public static final int ALL = 2;
  public static final int AUTHORIZATION = 7;
  public static final int INTEGER = 42;
  public static final int DECLARE = 21;
  public static final int DOUBLE = 26;
  public static final int LBRACE = 98;
  public static final int LPAREN = 96;
  public static final int NOT = 110;
  public static final int WHENEVER = 83;
  public static final int LE = 115;
  public static final int VIEW = 82;
  public static final int FLOAT = 30;
  public static final int GOTO = 35;
  public static final int NULLX = 49;
  public static final int PARAMETER = 56;
  public static final int EQ = 113;
  public static final int SQLCODE = 72;
  public static final int SMALLINT = 70;
  public static final int CHARACTER = 10;
  public static final int SQUOTE = 91;
  public static final int DOLLAR = 94;
  public static final int INTO = 43;
  public static final int SELECT = 68;
  public static final int NUMBER = 125;
  public static final int ALTER = 88;
  public static final int PLUS = 102;
  public static final int QUOTE = 92;
  public static final int PERCENT = 58;
  public static final int PRIVILEGES = 61;
  public static final int QUESTION = 117;
  public static final int EXISTS = 28;
  public static final int ORDER = 55;
  public static final int UNION = 77;
  public static final int DELETE = 23;
  public static final int SQLERROR = 73;
  public static final int DECIMAL = 20;
  public static final int AMMSC = 3;
  public static final int FOR = 31;
  public static final int ESCAPE = 27;
  public static final int DIV = 105;
  public static final int ADD = 89;
  public static final int PUBLIC = 63;
  public static final int PROCEDURE = 62;
  public static final int GRANT = 36;
  public static final int EOF = 0;
  public static final int BETWEEN = 8;
  public static final int ARITHMETIC = 124;
  public static final int WHERE = 84;
  public static final int DEFAULT = 22;
  public static final int COUNT = 15;
  public static final int CR = 118;
  public static final int MINUS = 103;
  public static final int IS = 44;
  public static final int FETCH = 29;
  public static final int UNIQUE = 78;
  public static final int IN = 39;
  public static final int DATE = 19;
  public static final int OR = 109;
  public static final int SET = 69;
  public static final int error = 1;
  public static final int ON = 52;
  public static final int CURRENT = 17;
  public static final int CONTINUE = 14;
  public static final int CURSOR = 18;
  public static final int DESC = 24;
  public static final int OF = 51;
  public static final int COLON = 101;
  public static final int CHECK = 11;
  public static final int BY = 9;
  public static final int VALUES = 81;
  public static final int SOME = 71;
  public static final int PRECISION = 59;
  public static final int ANY = 4;
  public static final int CREATE = 16;
  public static final int NUMERIC = 50;
  public static final int OPTION = 54;
  public static final int RENAME = 107;
  public static final int UPDATE = 79;
  public static final int INSERT = 41;
  public static final int PATTERNSTRING = 57;
  public static final int STRING = 122;
  public static final int FOREIGN = 32;
  public static final int PRIMARY = 60;
  public static final int COMPARISON = 123;
  public static final int AND = 108;
  public static final int COMMIT = 13;
  public static final int OPEN = 53;
  public static final int TO = 76;
  public static final int DROP = 106;
  public static final int WITH = 85;
  public static final int NE = 114;
  public static final int KEY = 46;
  public static final int HAVING = 38;
  public static final int DISTINCT = 25;
  public static final int LANGUAGE = 47;
  public static final int USER = 80;



}